### ISSUE TITLE
Paste - Issues

### ISSUE THREAD

**Issue by TheKye** [TheKye/Eco-WorldEdit#1]
when pasting, the pasted object should be pasted in the direction the player is facing, 
When pasting, the lowest point of the pasted object should be on the level or 1 level below where the player is standing at the time of pasting

Pasting doesn't delete plants trees

**Comment by TheKye** [comment]
System.InvalidCastException: Unable to cast object of type 'Eco.World.Blocks.EmptyBlock' to type 'Eco.Gameplay.Objects.WorldObjectBlock'.
   at Eco.Mods.WorldEdit.WorldEditManager.SetBlock(Type pType, Vector3i pPosition, UserSession pSession, Nullable 1 pSourcePosition, Block pSourceBlock, Byte[] pData)
   at Eco.Mods.WorldEdit.WorldEditUserData.LoadSelectionFromClipboard(User pUser, WorldEditUserData pWeud)
   at Eco.Mods.WorldEdit.WorldEditCommands.Paste(User user)
