### ISSUE TITLE
[Version] Prepare for ECO 9.5.0

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#48]
We need to prepare for this update

**Comment by StallEF** [comment]
**test on Eco 0.9.5.0 beta develop-397 - fail**

[Error] [Eco] Failed to start the server. Exception was Exception: ReflectionTypeLoadException
Message:Unable to load one or more of the requested types.

Source:System.Private.CoreLib

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Eco.Shared.Utils.ReflectionUtils.<>c.<GetFilteredAssemblyTypes>b__8_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Eco.Core.Serialization.SimpleSerializer.InitializeSerializableTypes()
   at Eco.Core.Serialization.SimpleSerializer..cctor()
System.TypeLoadException
Outer Exceptions:
Exception has been thrown by the target of an invocation.
One or more errors occurred. (The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.)
The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.

**Comment by TheKye** [comment]
Latest Version in 9.5 Testing works in 9.5 Staging Server Available on Steam

**Comment by StallEF** [comment]
Test on EcoPC_v0.9.5.0-beta-develop-430 - Pass 
I keep checking, but so far everything looks good
