### ISSUE TITLE
Failed to start the server. Exception was Exception: Exception

### ISSUE THREAD

**Issue by BrathuhnLiebhaber** [TheKye/Eco-WorldEdit#62]
When I try to create a selfhosted Server with only this mod I ran into an Error which disables me from starting/launching the server.
Logfile:
```
[21:58:24.227] [1] [ Info] [Eco] Eco Server 0.9.5.2 beta release-315
 
[21:58:24.242] [5] [ Info] [Eco] Starting PerformancePlugin                        ...  
[21:58:24.247] [5] [ Info] [Eco] Starting PerformancePlugin                        ... Finished in 0,005 sec
 
[21:58:24.247] [5] [ Info] [Eco] Starting ProfilingPlugin                          ...  
[21:58:24.247] [5] [ Info] [Eco] Starting ProfilingPlugin                          ... Finished in 0,000 sec
 
[21:58:24.247] [5] [ Info] [Eco] Starting MaintenancePlugin                        ...  
[21:58:24.265] [5] [ Info] [Eco] Starting MaintenancePlugin                        ... Finished in 0,019 sec
 
[21:58:24.265] [5] [ Info] [Eco] Server Initialization                             ...  
[21:58:24.277] [5] [ Info] [Eco] Starting FeaturesPlugin                           ...  
[21:58:24.277] [5] [ Info] [Eco] Starting FeaturesPlugin                           ... Finished in 0,013 sec
 
[21:58:24.290] [5] [ Info] [Eco] Starting BalancePlugin                            ...  
[21:58:24.290] [5] [ Info] [Eco] Starting BalancePlugin                            ... Finished in 0,003 sec
 
[21:58:24.290] [5] [ Info] [Eco] Starting NetworkManager                           ...  
[21:58:24.335] [5] [ Info] [Eco] Starting NetworkManager                           ... Finished in 0,035 sec
 
[21:58:24.335] [5] [ Info] [Eco] Starting DifficultySettings                       ...  
[21:58:24.380] [5] [ Info] [Eco] Starting DifficultySettings                       ... Finished in 0,044 sec
 
[21:58:24.380] [5] [ Info] [Eco] Starting ModKitPlugin                             ...  
[21:58:25.493] [1] [ Info] [Eco] Mods recompiled with errors.
 
[21:58:25.515] [1] [ Info] [Eco] C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Mods\UserCode\WorldEdit\CoreExtensions\DoorObject.cs(8,49): error CS0535: 'DoorObject' does not implement interface member 'IWireContainer.Wires'
 
[21:58:25.515] [1] [ Info] [Eco] C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Mods\UserCode\WorldEdit\CoreExtensions\DoorObject.cs(12,9): error CS1061: 'DoorObject' does not contain a definition for 'OpensOut' and no accessible extension method 'OpensOut' accepting a first argument of type 'DoorObject' could be found (are you missing a using directive or an assembly reference?)
 
[21:58:25.515] [5] [ Info] [Eco] Starting ModKitPlugin                             ... Finished in 1,136 sec
 
[21:58:25.515] [5] [ Info] [Eco] Server Initialization                             ... Finished in 1,251 sec
 
[21:58:25.528] [1] [Error] [Eco] Failed to start the server. Exception was Exception: Exception
Message:C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Mods\UserCode\WorldEdit\CoreExtensions\DoorObject.cs(8,49): error CS0535: 'DoorObject' does not implement interface member 'IWireContainer.Wires'
Source:Eco.ModKit

System.Exception: C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Mods\UserCode\WorldEdit\CoreExtensions\DoorObject.cs(8,49): error CS0535: 'DoorObject' does not implement interface member 'IWireContainer.Wires'
   at Eco.ModKit.RoslynCompiler.HandleCompilerError(ImmutableArray`1 diagnostics)
   at Eco.ModKit.RoslynCompiler.Compile()
   at Eco.ModKit.RoslynCompiler..ctor(String modsAssemblyPath)
   at Eco.ModKit.ModKitPlugin..ctor()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
 
[21:58:25.528] [1] [ Info] [Eco] Shutdown finished
 

```
Any ideas how to fix it?

**Comment by Tavren** [comment]
Problem causing file removed, sadly door placement fix no longer working
