### ISSUE TITLE
Eco 9.7.6 - Error during new server startup

### ISSUE THREAD

**Issue by ixolan** [TheKye/Eco-WorldEdit#69]
Hello, 
I installed the last releasse version of Worldedit (v2.4.0) and get the follwing error during startup of the server:

<code>[06:36:30] Failed to start the server. Exception was Exception: MissingMethodException
Message:Method not found: 'Void Eco.Shared.Utils.Log.WriteWarningLineLoc(System.FormattableString)'.
Source:WorldEdit
System.MissingMethodException: Method not found: 'Void Eco.Shared.Utils.Log.WriteWarningLineLoc(System.FormattableString)'.
   at Eco.Mods.WorldEdit.WorldEditManager.UpdateBlueprintList()
   at Eco.Mods.WorldEdit.EcoWorldEdit.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
[06:36:30] Shutdown finished</code>

Running a  eco as a docker container (official container from eco).

Server starts without worldedit without poblems.

**Comment by StallEF** [comment]
For current Eco 9.7.6 need use WE 2.5.0
https://eco.old.mod.io/ecoworldedit

the error can also be related to the inability to read Blueprint storage directory in the Linux system

**Comment by ixolan** [comment]
With 2.5.0 version no startup problems.
