### ISSUE TITLE
Crash server - Update eco v10.1.0

### ISSUE THREAD

**Issue by FrBeyond** [TheKye/Eco-WorldEdit#79]
`Failed to start the server. Exception was Exception: MissingMethodException
Message:Attempted to access a missing method.
Source:System.Private.CoreLib

System.MissingMethodException: Attempted to access a missing method.
   at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, ReadOnlySpan`1 typeInstantiationContext, ReadOnlySpan`1 methodInstantiationContext)
   at System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at Eco.Core.Controller.CoreAttributeExtensions.IsSyncToViewOrAutogen(MemberInfo member)
   at Eco.Core.Controller.ControllerMarshalerService.<>c.<GetAllControllerMethods>b__23_0(MethodInfo method)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at Eco.Core.Controller.ControllerMarshalerService.BuildMethods(ControllerMarshaler marshaler)
   at Eco.Core.Controller.ControllerMarshalerService.BuildClassMarshaler(ControllerMarshaler marshaler)
   at Eco.Core.Controller.ControllerMarshalerService.<>c.<CreateMarshalers>b__7_0(IControllerMarshaler marshaler, ControllerMarshalerService self)
   at Eco.Shared.Utils.EnumerableExtensions.<>c__DisplayClass52_0`2.<ParallelForEach>b__0(T i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.) (One or more errors occurred. (One or more errors occurred. (Attempted to access a missing method.)))
Exception has been thrown by the target of an invocation.
One or more errors occurred. (Attempted to access a missing method.)`

**Comment by FrBeyond** [comment]
![image](https://github.com/TheKye/Eco-WorldEdit/assets/77362457/7617e658-1966-4285-968c-bfb4893f173c)

**Comment by TheKye** [comment]
what other mods are present on the server?

**Comment by FrBeyond** [comment]
> what other mods are present on the server?

I have only world edit on a fresh server install :)

**Comment by FrBeyond** [comment]
When i try with Eco-worldEdit-master, who have little code uptade, i have another error message : 
![image](https://github.com/TheKye/Eco-WorldEdit/assets/77362457/6b76ab95-e459-4749-b419-bb9d8b7b10a5)

**Comment by TheKye** [comment]
can you translate that for me please >.<

**Comment by FrBeyond** [comment]
> pl

Oo sorry, it's in french xD 
the log say : Newtonsoft not found 

I just see there is a new version 10.1.1 --> downloaded it and same crash

**Comment by TheKye** [comment]
can you try this version please
[WorldEdit.zip](https://github.com/TheKye/Eco-WorldEdit/files/13985471/WorldEdit.zip)

**Comment by FrBeyond** [comment]
> can you try this version please [WorldEdit.zip](https://github.com/TheKye/Eco-WorldEdit/files/13985471/WorldEdit.zip)

It's working 
now i try in game command

**Comment by FrBeyond** [comment]
Select and copy past working 
cut paste working 
rotate working
Import and export working
undo working 
del working
wand working 

Expand when i look on the floor or sky doen'st work (this problem already know)

**Comment by StallEF** [comment]
https://github.com/TheKye/Eco-WorldEdit/releases/tag/v2.6.3
