### ISSUE TITLE
AbandonedMutexException on v2.6.3 with Eco 0.10.1.4 beta release-603

### ISSUE THREAD

**Issue by AntonPerson** [TheKye/Eco-WorldEdit#82]
```
[00:13:09.863] [10] [Error] [Eco] Failed to start the server. Exception was Exception: AbandonedMutexException
Message:The wait completed due to an abandoned mutex.
Source:System.Private.CoreLib

System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at Eco.Server.PluginManager.OccupyGameServerAddress(NetworkManager networkManager)
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
 
[00:13:09.863] [10] [ Info] [Eco] Shutdown finished
 
[00:13:09.885] [10] [Error] [Eco] Errors report:
Failed to start the server. Exception was Exception: AbandonedMutexException
Message:The wait completed due to an abandoned mutex.
Source:System.Private.CoreLib

System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at Eco.Server.PluginManager.OccupyGameServerAddress(NetworkManager networkManager)
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
: 1
 ```

**Comment by Tavren** [comment]
This issue not related to WorldEdit, post it at game Discord channel. From what i can guess issue that server configured incorrectly or maybe port is taken by another application, again that is just my guess, ask help from the SLG.
