### ISSUE TITLE
Crash server - Update eco v0.11.0.0

### ISSUE THREAD

**Issue by Marshall1912** [TheKye/Eco-WorldEdit#86]
[01:29:45] Failed to start the server. Exception was Exception: TypeLoadException
Message:
Source:System.Private.CoreLib

System.TypeLoadException
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.<get_Signature>g__LazyCreateSignature|25_0()
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimePropertyInfo.GetIndexParametersNoCopy()
   at System.Attribute.GetIndexParameterTypes(PropertyInfo element)
   at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at Eco.Shared.Utils.ReflectionUtils.IsSerialized(MemberInfo member)
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.<>c.<GetProperties>b__11_0(PropertyInfo propertyInfo)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctByIterator[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Eco.Core.Serialization.Serializers.ClassSerializer`1.Initialize()
   at Eco.Core.Serialization.SimpleSerializer.<>c.<InitSerializers>b__40_1(IInitializableSerializer classSerializer)
   at Eco.Core.Utils.ThreadUtils.<>c__DisplayClass1_0`1.<SplitWork>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
One or more errors occurred. (One or more errors occurred. ())
One or more errors occurred. ()

![ServerConsole](https://github.com/user-attachments/assets/e8822a97-2077-40b9-87e1-15465723de53)

Currently the only Mod installed on a fresh server install:
![modFile](https://github.com/user-attachments/assets/ebf56f9a-2159-4407-a397-cef5c14e2e71)

**Comment by padmanek** [comment]
Thats just from trying to load V10 mod into V11 server which wont work.
Please be patient and wait for an update.

**Comment by StallEF** [comment]
Version 2.6.3 is not for work in Eco11.0. 
RC 2.7.0 can be found in discord and we work on paint block support now.
